kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-gateway-outbound
  namespace: mobile-apps
  generation: 827
  labels:
    app: api-gateway-outbound
  annotations:
    deployment.kubernetes.io/revision: '43'
spec:
  replicas: 6
  selector:
    matchLabels:
      app: api-gateway-outbound
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-gateway-outbound
        app.kubernetes.io/instance: api-gateway-outbound
        version: 1.0.36
      annotations:
        sidecar.istio.io/bootstrapOverride: envoy-custom-bootstrap-config
        sidecar.istio.io/proxyMemoryLimit: 256Mi
        prometheus.io/port: '8080'
        prometheus.io/path: /actuator/prometheus
        maxMsgLogLength: '8192'
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyMemory: 256Mi
        prometheus.io/scrape: 'true'
        logCollectorSystemLabel: mobile
    spec:
      restartPolicy: Always
      serviceAccountName: default
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/internal-gateway
                    operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - api-gateway-outbound
                topologyKey: datacenter
      terminationGracePeriodSeconds: 30
      dnsConfig:
        options:
          - name: ndots
            value: '2'
      securityContext:
        runAsUser: 100000
        runAsGroup: 200000
        fsGroup: 300000
      containers:
        - resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 600m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 5
          name: api-gateway-outbound
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xms512m -Xmx512m  -Duser.timezone=Europe/Moscow -Duser.country=
                -Duser.language=en -XX:+AlwaysActAsServerClassMachine 
                -Djavax.net.ssl.trustStore=/var/run/secrets/java.io/cacerts  
                -Dserver.port=8080
            - name: APP
              value: api-gateway-outbound
            - name: CONTAINER_NAME
              value: click-api-gateway
            - name: CONFIG_BRANCH
              value: 6534962c21d3335dbfdab8eba87b451b7e1e2f59
            - name: CONFIG_SERV
              value: config-server
            - name: SPRING_PROFILES_ACTIVE
              value: 'kube,prod,cloud,logstash'
            - name: LOGGING_PROFILE
              value: STAGE
            - name: LOGGING_CONFIG
              value: /var/run/logback-spring-kube-2.0.13.xml
            - name: spring.reactor.debug-agent.enabled
              value: 'true'
            - name: spring.cloud.config.discovery.enabled
              value: 'false'
            - name: spring.cloud.config.uri
              value: 'http://config-server.mobile-apps'
            - name: eureka.client.enabled
              value: 'false'
            - name: spring.zipkin.enabled
              value: 'false'
            - name: kube.enabled
              value: 'true'
            - name: CONTAINER_NAME
              value: api-gateway-outbound
            - name: APP
              value: api-gateway-outbound
            - name: MAX_MSG_LENGTH
              value: '8192'
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          volumeMounts:
            - name: custom-bootstrap-volume
              mountPath: /etc/istio/custom-bootstrap
            - name: logback
              mountPath: /var/run
            - name: cacerts
              mountPath: /var/run/secrets/java.io
            - name: tmpfs
              mountPath: /tmp
          terminationMessagePolicy: File
          image: 'eco.binary.bank.ru/click-api-gateway:1.0.36'
      serviceAccount: default
      volumes:
        - name: logback
          configMap:
            name: logback-config-2.0.13
            defaultMode: 420
        - name: custom-bootstrap-volume
          configMap:
            name: envoy-custom-bootstrap-config
            defaultMode: 420
        - name: cacerts
          secret:
            secretName: cacerts
            defaultMode: 420
        - name: tmpfs
          emptyDir: {}
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
