---
###==========================================
###  Vars for ALL groups of hosts
###==========================================
mms_docker_full_image             : "infra.binary.bank.ru/{{ mms_docker_image_name }}:{{ mms_docker_image_version }}"






flush_all                         : false
# поставить true, если хотим накатить всю инфру “одной кнопкой”
deploy_all_static                 : false
#manifest_dir                     : "{{ ansible_env.HOME }}/config"
mesos_rpm_name                    : 1
# host port range

# -------
# Manifests vars
# -------
logger_port                       : 514
logger_version                    : 1.3.4
logger_tags                       : forwarding,json

# --------
# Inframon
# --------
inframon_include_host_heartbeat   : true
support_user_for_es               : support_tools_reader
inframon_include_exporters        : true

# Node exporter
node_exporter_docker_image_version: v1.8.2
node_exporter_volumes:
  - "/data"
  - "/var/lib/docker"

node_exporter_filesystem_ignored_mount_points_regex: "^/(sys|proc|dev|host|etc|run|var/lib/docker/.+)($|/)"
